#!/usr/bin/env python3
"""Build the one-file CanMV deployment for automatic A4 tracking."""

import ast
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUTPUT = HERE / "k230_realtime_a4_standalone.py"
LOCAL_MODULES = {
    "puzzle_config",
    "puzzle_perf",
    "puzzle_geometry",
    "puzzle_image_strip",
    "puzzle_placement",
    "puzzle_realtime_state",
    "puzzle_vision",
    "k230_puzzle_planner",
    "realtime_a4_config",
    "puzzle_a4_boundary",
}


def _assigned_names(source):
    tree = ast.parse(source)
    names = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = (
            node.targets
            if isinstance(node, ast.Assign)
            else [node.target]
        )
        for target in targets:
            if (
                isinstance(target, ast.Name)
                and target.id.isupper()
            ):
                names.append(target.id)
    return names


def _filtered_source(path, omit_main=False, omit_guard=False):
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    omitted_lines = set()
    for node in ast.walk(tree):
        omit = False
        if isinstance(node, ast.Import):
            omit = any(
                alias.name in LOCAL_MODULES for alias in node.names
            )
        elif isinstance(node, ast.ImportFrom):
            omit = node.module in LOCAL_MODULES
        if omit:
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
    for node in tree.body:
        if (
            omit_main
            and isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == "main"
        ):
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
        if (
            omit_guard
            and isinstance(node, ast.If)
            and "__name__" in ast.unparse(node.test)
        ):
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
    return "\n".join(
        line
        for line_number, line in enumerate(
            source.splitlines(), 1
        )
        if line_number not in omitted_lines
    )


def _config_block():
    base_path = ROOT / "puzzle_config.py"
    override_path = HERE / "realtime_a4_config.py"
    base = base_path.read_text(encoding="utf-8")
    override = _filtered_source(override_path)
    base_names = _assigned_names(base)
    override_names = _assigned_names(
        override_path.read_text(encoding="utf-8")
    )
    lines = [
        base,
        "class _StandaloneConfig:",
        "    pass",
        "",
        "cfg = _StandaloneConfig()",
    ]
    lines.extend(
        "cfg.{0} = {0}".format(name) for name in base_names
    )
    lines.append(override)
    lines.extend(
        "cfg.{0} = {0}".format(name)
        for name in override_names
    )
    lines.append("cfg.STANDALONE_BUILD = True")
    return "\n".join(lines)


def main():
    sections = [
        "#!/usr/bin/env python3\n"
        '"""Generated shake-tolerant automatic-A4 CanMV planner."""\n'
        "# Generated by k230_realtime_a4/build_standalone.py.\n",
        _config_block(),
        _filtered_source(ROOT / "puzzle_perf.py"),
        _filtered_source(ROOT / "puzzle_geometry.py"),
        _filtered_source(ROOT / "puzzle_image_strip.py"),
        _filtered_source(ROOT / "puzzle_placement.py"),
        _filtered_source(ROOT / "puzzle_realtime_state.py"),
        _filtered_source(ROOT / "puzzle_vision.py"),
        _filtered_source(ROOT / "puzzle_a4_boundary.py"),
        _filtered_source(
            ROOT / "k230_puzzle_planner.py",
            omit_main=True,
            omit_guard=True,
        ),
        _filtered_source(HERE / "k230_realtime_a4.py"),
    ]
    OUTPUT.write_text(
        "\n\n".join(sections) + "\n",
        encoding="utf-8",
    )
    print(
        "BUILT,output={},bytes={}".format(
            OUTPUT, OUTPUT.stat().st_size
        )
    )


if __name__ == "__main__":
    main()
