#!/usr/bin/env python3
"""Build the simulator-backed one-file CanMV deployment."""

import argparse
import ast
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUTPUT = HERE / "k230_realtime_a4_simulator_standalone.py"
LOCAL_MODULES = {
    "puzzle_config",
    "puzzle_perf",
    "puzzle_geometry",
    "puzzle_simulator_planner",
    "puzzle_placement",
    "puzzle_realtime_state",
    "puzzle_vision",
    "k230_puzzle_planner",
    "realtime_a4_config",
    "puzzle_a4_boundary",
}


def _assigned_names(source):
    tree = ast.parse(source)
    names = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = (
            node.targets
            if isinstance(node, ast.Assign)
            else [node.target]
        )
        for target in targets:
            if (
                isinstance(target, ast.Name)
                and target.id.isupper()
            ):
                names.append(target.id)
    return names


def _filtered_source(path, omit_main=False, omit_guard=False):
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    omitted_lines = set()
    for node in ast.walk(tree):
        omit = False
        if isinstance(node, ast.Import):
            omit = any(
                alias.name in LOCAL_MODULES for alias in node.names
            )
        elif isinstance(node, ast.ImportFrom):
            omit = node.module in LOCAL_MODULES
        if omit:
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
    for node in tree.body:
        if (
            omit_main
            and isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == "main"
        ):
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
        if (
            omit_guard
            and isinstance(node, ast.If)
            and "__name__" in ast.unparse(node.test)
        ):
            omitted_lines.update(
                range(node.lineno, node.end_lineno + 1)
            )
    return "\n".join(
        line
        for line_number, line in enumerate(
            source.splitlines(), 1
        )
        if line_number not in omitted_lines
    )


def _config_block(simulator_validation):
    base_path = ROOT / "puzzle_config.py"
    override_path = HERE / "realtime_a4_config.py"
    base = base_path.read_text(encoding="utf-8")
    override = _filtered_source(override_path)
    base_names = _assigned_names(base)
    override_names = _assigned_names(
        override_path.read_text(encoding="utf-8")
    )
    lines = [
        base,
        "class _StandaloneConfig:",
        "    pass",
        "",
        "cfg = _StandaloneConfig()",
    ]
    lines.extend(
        "cfg.{0} = {0}".format(name) for name in base_names
    )
    lines.append(override)
    lines.extend(
        "cfg.{0} = {0}".format(name)
        for name in override_names
    )
    lines.append("cfg.STANDALONE_BUILD = True")
    lines.append("cfg.PLANNER_BACKEND = 'simulator'")
    lines.append(
        "cfg.SIMULATOR_PLANNER_VALIDATION = {!r}".format(
            simulator_validation
        )
    )
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--simulator-validation",
        choices=("local", "upstream"),
        default="upstream",
        help=(
            "upstream follows confirmed competition proposal semantics; "
            "local applies the stricter geometric A/B gates"
        ),
    )
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    output = args.output or OUTPUT
    sections = [
        "#!/usr/bin/env python3\n"
        '"""Generated simulator-backed realtime A4 CanMV planner."""\n'
        "# Generated by k230_realtime_a4/build_standalone.py.\n",
        _config_block(args.simulator_validation),
        _filtered_source(ROOT / "puzzle_perf.py"),
        _filtered_source(ROOT / "puzzle_geometry.py"),
        _filtered_source(ROOT / "puzzle_simulator_planner.py"),
    ]
    sections.extend([
        _filtered_source(ROOT / "puzzle_placement.py"),
        _filtered_source(ROOT / "puzzle_realtime_state.py"),
        _filtered_source(ROOT / "puzzle_vision.py"),
        _filtered_source(ROOT / "puzzle_a4_boundary.py"),
        _filtered_source(
            ROOT / "k230_puzzle_planner.py",
            omit_main=True,
            omit_guard=True,
        ),
        _filtered_source(HERE / "k230_realtime_a4.py"),
    ])
    output.write_text(
        "\n\n".join(sections) + "\n",
        encoding="utf-8",
    )
    print(
        "BUILT,output={},bytes={}".format(
            output, output.stat().st_size
        )
    )


if __name__ == "__main__":
    main()
