#!/usr/bin/env python3
"""Build the one-file CanMV deployment script.

CanMV IDE executes the open editor buffer but does not automatically copy its
local imports to the board.  This builder mechanically combines configuration,
geometry, native vision, and the hardware entrypoint so the firmware needs only
one submitted script.
"""

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "k230_puzzle_planner_standalone.py"


def _without_local_imports(path):
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    omitted_lines = set()
    local_modules = {
        "puzzle_config",
        "puzzle_perf",
        "puzzle_geometry",
        "puzzle_vision",
        "puzzle_a4_boundary",
    }
    for node in ast.walk(tree):
        omit = False
        if isinstance(node, ast.Import):
            omit = any(
                alias.name in local_modules for alias in node.names
            )
        elif isinstance(node, ast.ImportFrom):
            omit = node.module in local_modules
        if omit:
            for line_number in range(
                node.lineno, node.end_lineno + 1
            ):
                omitted_lines.add(line_number)
    lines = source.splitlines()
    return "\n".join(
        line
        for line_number, line in enumerate(lines, 1)
        if line_number not in omitted_lines
    )


def _config_block(path):
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    names = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = (
            node.targets
            if isinstance(node, ast.Assign)
            else [node.target]
        )
        for target in targets:
            if (
                isinstance(target, ast.Name)
                and target.id.isupper()
            ):
                names.append(target.id)
    assignments = "\n".join(
        "cfg.{0} = {0}".format(name) for name in names
    )
    return (
        source
        + "\n\nclass _StandaloneConfig:\n"
        + "    pass\n\n"
        + "cfg = _StandaloneConfig()\n"
        + assignments
        + "\ncfg.STANDALONE_BUILD = True\n"
    )


def main():
    sections = [
        "#!/usr/bin/env python3\n"
        '"""Generated single-file CanMV K230 A4 puzzle planner."""\n'
        "# Generated by build_k230_standalone.py; edit source modules instead.\n",
        _config_block(ROOT / "puzzle_config.py"),
        _without_local_imports(ROOT / "puzzle_perf.py"),
        _without_local_imports(ROOT / "puzzle_geometry.py"),
        _without_local_imports(ROOT / "puzzle_vision.py"),
        _without_local_imports(ROOT / "puzzle_a4_boundary.py"),
        _without_local_imports(ROOT / "k230_puzzle_planner.py"),
    ]
    OUTPUT.write_text(
        "\n\n".join(sections) + "\n",
        encoding="utf-8",
    )
    print("BUILT,output={},bytes={}".format(
        OUTPUT, OUTPUT.stat().st_size
    ))


if __name__ == "__main__":
    main()
